#!/bin/bash
#### AUTOSTART ####

#### MONITORS ####
{{#if multi_monitor}}
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9
{{else}}
bspc monitor -d 1 2 3 4 5 6 7 8 9
{{/if}}

# map2 -d /home/b3nj4m1n/dotfiles/files/map2/devices.list /home/b3nj4m1n/dotfiles/files/map2/test.m2 &
setxkbmap de &

# Daemons & stuff
sxhkd ~/.config/sxhkd/sxhkdrc_bspc &
picom --experimental-backends &
dunst &
mpd &
redshift &
/usr/bin/scripts/wally.sh &
feh --bg-scale /usr/share/wallpapers/custom/moonRising.png &
# emacs --daemon &
aw-server-rust &
greenclip daemon &
unclutter --idle 2 &
betterlockscreen -u /usr/share/wallpapers/custom/samuel-inkilainen-arctic-spirit-with-signature.jpg &
syncthing -no-browser &
/home/b3nj4m1n/.config/polybar/polybar.sh &
mpc idleloop | while read line; do pkill lemonblocks -5; done &
bspc subscribe desktop | while read line; do pkill lemonblocks -4; done &


# Programms
/usr/bin/scripts/open-move.sh firefox 2

# Scratchpads
killall cmus && killall neomutt && killall calcurse
alacritty --class "ncmpcpp" -e "ncmpcpp" &
alacritty --class "neomutt" --dimensions 226 60 --position 50 60  -e "neomutt" &
alacritty --class "calcurse" -e "calcurse" &

# ~/.config/polybar/polybar.sh

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  3
bspc config window_gap                    10
bspc config top_padding                   30
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "{{ colors.scd }}"
bspc config active_border_color	          "{{ colors.prm }}"
bspc config focused_border_color	      "{{ colors.prm }}"
bspc config presel_feedback_color	      "{{ colors.prm_dim }}"
bspc config urgent_border_color 	      "{{ colors.c1 }}"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

# bspc rule -a init_firefox desktop='^2'
# bspc rule -a discord desktop='^8'
# bspc rule -a Anki desktop='^6'
# bspc rule -a init_thunderbird desktop='^7'
# bspc rule -a KeeWeb:keeweb desktop='^10'
# bspc rule -a *:SPLASH state=floating 
bspc rule -a Zathura state='tiled'
bspc rule -a Emacs state='tiled'

# Scratchpad inital start
bspc rule -a Alacritty:ncmpcpp desktop='^10' state='floating' hidden='true' sticky='true'
bspc rule -a Alacritty:neomutt desktop='^10' state='floating' hidden='true' sticky='true'
bspc rule -a Alacritty:calcurse desktop='^10' state='floating' hidden='true' sticky='true'

bspc desktop -f 1
