#!/bin/bash
#### AUTOSTART ####

# Daemons & stuff
sxhkd &
picom --experimental-backends &
dunst &
# ~/wally.sh -r -t nature &
feh --bg-scale /usr/share/wallpapers/custom/samuel-inkilainen-arctic-spirit-with-signature.jpg &
# ~/.config/polybar/polybar.sh
setxkbmap de &
# python ~/dotfiles/scripts/bspwm-swallow.py &
# Programms


firefox --class="init_firefox" &
alacritty --class "cmus" -e "cmus" &
# discord &
# anki &
# thunderbird --class "init_thunderbird" &
# keeweb &
syncthing &
betterlockscreen -u /usr/share/wallpapers/custom/samuel-inkilainen-arctic-spirit-with-signature.jpg &
start-lemonbar.sh &

# ~/.config/polybar/polybar.sh

#### MONITORS ####
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  3
bspc config window_gap                    10
bspc config top_padding                   30
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#00ff99"
bspc config active_border_color	              "#ff0066"
bspc config focused_border_color	      "#ff0066"
bspc config presel_feedback_color	      "#00ff94"
bspc config urgent_border_color 	      "#ff1b1c"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

bspc rule -a init_firefox desktop='^2'
bspc rule -a init_thunderbird desktop='^7'
bspc rule -a Alacritty:cmus desktop='^9'
bspc rule -a discord desktop='^8'
bspc rule -a Anki desktop='^6'
bspc rule -a KeeWeb:keeweb desktop='^10'
bspc rule -a *:SPLASH state=floating 

bspc desktop -f 1
