#!/bin/bash

############### Bspwm ###############

# Quit/Restart bspwm
super + shift + {q,r}
    bspc {quit,wm -r}

# Close current application
alt + shift + c
    bspc node -c

# alternate between the tiled and monocle layout
super + m
    bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
    bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
    bspc node -s biggest

# set the window state
super + {t,shift + t,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
    bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
alt + {_,shift + }{h,j,k,l}
    bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
# alt + {p,b,comma,period}
# 	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
alt + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
alt + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
alt + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
alt + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
alt + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
alt + shift + {z,u,i,o}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + shift + shift + {z,u,i,o}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}


############### Essential Keybindings ###############

# Open terminal
alt + Return
    alacritty

# Open application launcher
# Alt + d
alt + d
    dmenu_run

# Reload sxhkd config files
super + Escape
    pkill -USR1 -x sxhkd

############### General ###############

# Change wallpaper
# Super + w
super + w
    bash ~/wally.sh -r -t nature

# Lock input
# Alt + q
alt + q
   betterlockscreen -l "blur" 

# Emoji menu
super + u
    bash ~/dotfiles/scripts/emoji-picker.sh

############### Volume Control ###############

# Increase volume
XF86AudioRaiseVolume
    amixer sset 'Master' 3%+
alt + shift + plus
    amixer sset 'Master' 1%+


# Decrease volume
XF86AudioLowerVolume
    amixer sset 'Master' 3%-
alt + shift + minus
    amixer sset 'Master' 1%-


# Mute
XF86AudioMute
    amixer -D pulse set 'Master' toggle

############### Player Control ###############

# Pause playback
XF86AudioPlay
    cmus-remote -u
# Alt + p
alt + p
    cmus-remote -u


# Next song
XF86AudioNext
    cmus-remote -n
# Alt + n
alt + n
    cmus-remote -n


# Previous song
XF86AudioPrev
    cmus-remote -r
# Alt + m
alt + m
    cmus-remote -r


############### Launch Programms ###############

# firefox, nautilus, cli-visualizer, keeweb
# Alt + v | f n v k
alt + v: {f,n,v,k}
    {firefox,nautilus,alacritty -e "vis",keeweb} & \
    pkill -ALRM sxhkd


############### Cmus Control ###############

# restart, open, fav
# Alt + c | r o f
alt + c: {r,o,f}
    {bash ~/dotfiles/scripts/reimport-playlists-cmus.sh,bash ~/dotfiles/scripts/play-song.sh,bash ~/dotfiles/scripts/fav-song.sh} & \
    pkill -ALRM sxhkd


############### Scripts ###############

# german, dvorak, programmer dvorak, english
# Super + Shift + i
super + ctrl + shift + i
    bash ~/dotfiles/scripts/keyboard-layout-switcher.sh

# Draw terminal
alt + shift + Return
    bash ~/dotfiles/scripts/draw-terminal.sh

# Take screenshot
super + p
    bash ~/dotfiles/scripts/take-screenshot.sh


############### Other ###############

# Kill picom
super + F1
    killall picom

# Start picom
super + shift + F1
    picom --experimental-backends &
