#!/bin/bash

############### Bspwm ###############

# Quit/Restart bspwm
super + shift + {q,r}
    bspc {quit,wm -r}

# Close current application
alt + shift + c
    bspc node -c

# Show menu with hidden windows and unhide selection
# super + h:
#     wid=$(for id in $(bspc query -N -d focused -n .hidden.local.window); do xprop -id "$id" WM_NAME WM_CLASS | grep -o '".*"' | sed 's/", "/\n/g' | sed 's/"//g' | sed "s/^/ | /g" | tr '\n' ' ' | sed "s/^/$id/g" | sed "s/$/\n/g"; done | rofi -dmenu | cut -d '|' -f 1 | sed 's/ //g'); bspc node "$wid" --flag hidden=off

# alternate between the tiled and monocle layout
# super + m
#     bspc desktop -l next

# send the newest marked node to the newest preselected node
# super + y
#     bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
# super + g
#     bspc node -s biggest

# set the window state
super + {t,shift + t,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
    bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
alt + {h,j,k,l}
    bspc node -f {west,south,north,east}

# Move node in the given direction
alt + shift + {h,j,k,l}
    bash /usr/bin/scripts/bspwm-swap-or-move-in.sh  {west,south,north,east}
    # bash /usr/bin/scripts/bspwm-smart-move.sh  {west,south,north,east}

# focus the node for the given path jump
# alt + {p,b,comma,period}
# 	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
# super + {_,shift + }c
# 	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
# super + bracket{left,right}
# 	bspc desktop -f {prev,next}.local; pkill lemonblocks -4

# focus the last node/desktop
# super + {grave,Tab}
# 	bspc {node,desktop} -f last; pkill lemonblocks -4

# focus the older or newer node in the focus history
# super + {o,i}
# 	bspc wm -h off; \
# 	bspc node {older,newer} -f; \
# 	bspc wm -h on; pkill lemonblocks -4

# focus or send to the given desktop
alt + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# Cycle through desktops
alt + Tab
    bspc desktop next -f; pkill lemonblocks -4

#
# preselect
#

# preselect the direction
alt + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
alt + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
alt + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
# alt + ctrl + shift + space
# 	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
alt + shift + {y,u,i,o}
    /usr/bin/scripts/bspwm-resize.sh {west,south,north,east}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# Rotate tree
alt + shift + {d,a}
    bspc node @/ -C {forward,backward}

# Smart presel
alt + shift + Return
    /usr/bin/scripts/bspwm-smart-presel.sh

# Dynamic gaps.
super + shift + {minus,plus}
	bspc config -d focused window_gap "$(($(bspc config -d focused window_gap) {-,+} 5 ))"

# Create receptacle
alt + i
    bspc node -i


