#!/bin/bash

############### Bspwm ###############

# Quit/Restart bspwm
super + shift + {q,r}
    bspc {quit,wm -r}

# Close current application
alt + shift + c
    bspc node -c

# Show menu with hidden windows and unhide selection
super + h:
    wid=$(for id in $(bspc query -N -d focused -n .hidden.local.window); do xprop -id "$id" WM_NAME WM_CLASS | grep -o '".*"' | sed 's/", "/\n/g' | sed 's/"//g' | sed "s/^/ | /g" | tr '\n' ' ' | sed "s/^/$id/g" | sed "s/$/\n/g"; done | dmenu | cut -d '|' -f 1 | sed 's/ //g'); bspc node "$wid" --flag hidden=off

# alternate between the tiled and monocle layout
# super + m
#     bspc desktop -l next

# send the newest marked node to the newest preselected node
# super + y
#     bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
# super + g
#     bspc node -s biggest

# set the window state
super + {t,shift + t,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
# super + ctrl + {m,x,y,z}
#     bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
alt + {h,j,k,l}
    bspc node -f {west,south,north,east}

# Move node in the given direction
alt + shift + {h,j,k,l}
    bash /usr/bin/scripts/bspwm-smart-move.sh  {west,south,north,east}

# focus the node for the given path jump
# alt + {p,b,comma,period}
# 	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
# super + {_,shift + }c
# 	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
# super + bracket{left,right}
# 	bspc desktop -f {prev,next}.local; pkill lemonblocks -4

# focus the last node/desktop
# super + {grave,Tab}
# 	bspc {node,desktop} -f last; pkill lemonblocks -4

# focus the older or newer node in the focus history
# super + {o,i}
# 	bspc wm -h off; \
# 	bspc node {older,newer} -f; \
# 	bspc wm -h on; pkill lemonblocks -4

# focus or send to the given desktop
alt + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'; pkill lemonblocks -4

#
# preselect
#

# preselect the direction
alt + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
alt + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
alt + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
# alt + ctrl + shift + space
# 	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
alt + shift + {z,u,i,o}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + shift + {z,u,i,o}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}


############### Essential Keybindings ###############

# Open terminal
alt + Return
    alacritty

# Open application launcher
# Alt + d
alt + d
    dmenu_run

# Reload sxhkd config files
super + Escape
    pkill -USR1 -x sxhkd

############### General ###############

# Change wallpaper
# Super + w
super + w
    bash ~/wally.sh -r -t nature

# Lock input
# Alt + q
alt + q
   betterlockscreen -l "blur" 

# Emoji menu
super + u
    bash /usr/bin/scripts/emoji-picker.sh

############### Volume Control ###############

# Increase volume
XF86AudioRaiseVolume
    amixer sset 'Master' 3%+; pkill lemonblocks -6
alt + shift + plus
    amixer sset 'Master' 1%+; pkill lemonblocks -6


# Decrease volume
XF86AudioLowerVolume
    amixer sset 'Master' 3%-; pkill lemonblocks -6
alt + shift + minus
    amixer sset 'Master' 1%-; pkill lemonblocks -6


# Mute
XF86AudioMute
    amixer -D pulse set 'Master' toggle; pkill lemonblocks -6

############### Player Control ###############

# Pause playback
XF86AudioPlay
    cmus-remote -u; pkill lemonblocks -5
# Alt + p
alt + p
    cmus-remote -u; pkill lemonblocks -5


# Next song
XF86AudioNext
    cmus-remote -n; pkill lemonblocks -5
# Alt + n
alt + n
    cmus-remote -n; pkill lemonblocks -5


# Previous song
XF86AudioPrev
    cmus-remote -r; pkill lemonblocks -5
# Alt + m
alt + m
    cmus-remote -r; pkill lemonblocks -5


############### Launch Programms ###############

# firefox, nautilus, cli-visualizer, keeweb
# Alt + v | f n v k
alt + v: {f,n,v,k}
    {firefox,nautilus,alacritty -e "vis",keeweb} & \
    pkill -ALRM sxhkd


############### Cmus Control ###############

# restart, open, fav
# Alt + c | r o f
alt + c: {r,o,f}
    {bash /usr/bin/scripts/reimport-playlists-cmus.sh,bash /usr/bin/scripts/play-song.sh,bash /usr/bin/scripts/fav-song.sh} & \
    pkill -ALRM sxhkd


############### Scripts ###############

# german, dvorak, programmer dvorak, english
# Super + Shift + i
super + ctrl + shift + i
    bash /usr/bin/scripts/keyboard-layout-switcher.sh

# Draw terminal
alt + shift + Return
    bash /usr/bin/scripts/draw-terminal.sh

# Take screenshot
super + p
    bash /usr/bin/scripts/take-screenshot.sh


############### Other ###############

# Show sxhkd help page
F1
    bash /usr/bin/scripts/sxhkd-help-page.sh

# Kill picom
super + F2
    killall picom

# Start picom
super + shift + F2
    picom --experimental-backends &

# Mount drives
super + F3
    bash /usr/bin/scripts/dmenu-mount.sh

# Unmount drives
super + shift + F3
    bash /usr/bin/scripts/dmenu-umount.sh

# Restart lemonbar
super + F4
    bash /usr/bin/start-lemonbar.sh

# Neomutt scratchpad
alt + u:
    bash /usr/bin/scripts/bspwm-scratchpad.sh "neomutt"
# Calcurse scratchpad
alt + t:
    bash /usr/bin/scripts/bspwm-scratchpad.sh "calcurse"
# Cmus scratchpad
alt + r:
    bash /usr/bin/scripts/bspwm-scratchpad.sh "cmus"




