#!/usr/bin/env sh

############### Essential Keybindings ###############

super + F4
    alacritty -e "cmatrix"

# Open terminal with tmux
super + Return
    alacritty -e "tmux"
# Open terminal without tmux
alt + Return
    alacritty
# Open terminal and attach to tmux
super + ctrl + t
    alacritty -e "tmux" "attach"

# Open application launcher
# Alt + d
super + d
    rofi -show drun
    # rofi -show run

# Reload sxhkd config files
super + Escape
    pkill -USR1 -x sxhkd

############### General ###############

# Lock input
# Alt + q
super + q
   betterlockscreen -l "blur" 

# Emoji menu
alt + u
    /home/b3nj4m1n/.local/share/bin/emoji-picker.sh

############### Volume Control ###############

# Increase volume
XF86AudioRaiseVolume
    amixer sset 'Master' 3%+; pkill lemonblocks -6
alt + shift + plus
    amixer sset 'Master' 1%+; pkill lemonblocks -6


# Decrease volume
XF86AudioLowerVolume
    amixer sset 'Master' 3%-; pkill lemonblocks -6
alt + shift + minus
    amixer sset 'Master' 1%-; pkill lemonblocks -6


# Mute
XF86AudioMute
    amixer -D pulse set 'Master' toggle; pkill lemonblocks -6

############### Brightness Control ###############

# More brightness
XF86MonBrightnessUp
    brightnessctl s +10%
super + shift + plus
    brightnessctl s +10%

# Less brightness
XF86MonBrightnessDown
    brightnessctl s 10%-
super + shift + minus
    brightnessctl s 10%-

############### Player Control ###############

# Pause playback
XF86AudioPlay
    mpc toggle
# Alt + p
super + p
    mpc toggle


# Next song
XF86AudioNext
    mpc next
# Alt + n
super + n
    mpc next


# Previous song
XF86AudioPrev
    mpc prev
# Alt + m
super + m
    mpc prev


############### Launch Programms ###############

# firefox, nautilus, cli-visualizer, keeweb
# Alt + v | f n v k
#alt + v: {f,n,v,k}
#    {firefox,nautilus,alacritty -e "vis",keeweb} & \
#    pkill -ALRM sxhkd


############### Cmus Control ###############

# restart, open, fav
# Alt + c | r o f
alt + c: {r,o,f}
    {bash ~/.local/share/bin/mpd-open-playlist.sh,bash ~/.local/share/bin/play-song.sh,bash ~/.local/share/bin/fav-song.sh} & \
    pkill -ALRM sxhkd


############### Scripts ###############

# german, dvorak, programmer dvorak, english
# Super + Shift + i
super + ctrl + shift + i
    /home/b3nj4m1n/.local/share/bin/keyboard-layout-switcher.sh

# Draw terminal
#alt + super + Return
#    bash /usr/bin/scripts/draw-terminal.sh

# Take screenshot
super + p
    flameshot gui -p ~/Pictures/screenshots


############### Other ###############

# Show sxhkd help page
F1
    /home/b3nj4m1n/.local/share/bin/sxhkd-help-page.sh

# Kill picom
super + F2
    killall picom

# Start picom
super + shift + F2
    picom --experimental-backends &

## Mount drives
#super + F3
#    bash /usr/bin/scripts/dmenu-mount.sh
#
## Unmount drives
#super + shift + F3
#    bash /usr/bin/scripts/dmenu-umount.sh

# Restart lemonbar
#super + F4
#    bash /usr/bin/start-lemonbar.sh

# Kill emacs server
#super + F5
#    /usr/bin/emacsclient -e '(kill-emacs)'

# Start emacs server
#super + shift + F5
#    /usr/bin/emacs --daemon &

# Neomutt scratchpad
#alt + u:
#    bash /usr/bin/scripts/bspwm-scratchpad.sh "neomutt"
# Calcurse scratchpad
#alt + t:
#    bash /usr/bin/scripts/bspwm-scratchpad.sh "calcurse"
# Cmus scratchpad
#alt + r:
#    bash /usr/bin/scripts/bspwm-scratchpad.sh "ncmpcpp"

# Open calculator
alt + g:
    /bin/rofi -show calc -modi calc -no-show-match -no-sort | xclip -selection clipboard

# Show clipboard history
alt + h:
    /bin/rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'

# Replace clipboard with sha256 hash of clipboard
ctrl + super + c:
    /bin/xclip -o -sel clip | /bin/sha256sum | /bin/cut -f1 -d' ' | /bin/tr -d '\n' | /bin/xclip -sel clip
