-- [nfnl] Compiled from fnl/init.fnl by https://github.com/Olical/nfnl, do not edit.
def(util, require("util"))
def(options, require("options"))
def(plugins, require("plugins"))
paq["init-lazy"]()
def(keymaps, require("keymaps"))
def(__fnl_global__feline_2dconfig, require("feline-config"))
def(__fnl_global__plugin_2dconfig, require("plugin-config"))
def(__fnl_global__lsp_2dutil, require("lsp-util"))
__fnl_global__plugin_2dconfig.colorscheme()
__fnl_global__plugin_2dconfig["watch-mode-changes"]()
__fnl_global__plugin_2dconfig["indent-blankline"]()
__fnl_global__plugin_2dconfig.leap()
__fnl_global__plugin_2dconfig.autopairs()
__fnl_global__plugin_2dconfig["nvim-surround"]()
__fnl_global__plugin_2dconfig["nvim-colorizer"]()
__fnl_global__plugin_2dconfig["nvim-treesitter"]()
__fnl_global__plugin_2dconfig.trouble()
__fnl_global__plugin_2dconfig["nvim-cmp"]()
__fnl_global__plugin_2dconfig.luasnip()
__fnl_global__plugin_2dconfig.gitsigns()
__fnl_global__plugin_2dconfig.conjure()
__fnl_global__plugin_2dconfig.netrw()
__fnl_global__plugin_2dconfig.ufo()
__fnl_global__plugin_2dconfig.dap()
def(highlight, require("highlight"))
highlight["create-groups-telescope"]("normal")
highlight["create-groups-ufo"]("normal")
highlight["create-groups-cmp"]()
return highlight["create-groups-cursorword"]()
