packages = [
    "redshift",
    "desktop",
    "picom",
    "tmux",
    "neovim",
    "zsh",
    "bspwm",
    "sxhkd",
    "zathura",
    "mirage",
    "lightdm",
    "ssh",
    "scripts",
    "emacs",
    "polybar",
    "rofi",
    "ncmcpp",
    "neomutt",
    "bash",
    "fish",
    "ranger",
    "system",
    "gtk",
    "fonts",
    "shrc",
    "dracula",
    "firamono",
    "alacritty",
    "starship",
    "dunst",
    "anki",
    "cli-visualizer",
]

[files]
# "files/firefox/user.js" = "~/.mozilla/firefox/ogee8zmb.default-release/user.js"
# "files/firefox/userChrome.css" = "~/.mozilla/firefox/ogee8zmb.default-release/chrome/userChrome.css"
# "files/firefox/userContent.css" = "~/.mozilla/firefox/ogee8zmb.default-release/chrome/userContent.css"
