packages = [
    "laptop",
    "tmux",
    "neovim",
    "zsh",
    "bspwm",
    "sxhkd",
    "zathura",
    "lightdm",
    "ssh",
    "scripts",
    "emacs",
    "polybar",
    "rofi",
    "ncmcpp",
    "bash",
    "fish",
    "ranger",
    "profile",
    "gtk",
    "fonts",
    "shrc",
    "dracula",
    "firamono",
    "alacritty",
    "starship",
    "dunst",
    "anki",
    "cli-visualizer",
]
