packages = [
    "adelie",
    "sway",
    "tofi",
    "wofi",
    "tmux",
    "neovim",
    "zsh",
    "lisp",
    "taskwarrior",
    "ssh",
    "ncmcpp",
    "neomutt",
    "bash",
    "fish",
    "ranger",
    "system",
    "shrc",
    "catppuccin",
    "fantasque",
    "alacritty",
    "wezterm",
    "starship",
    "npm",
    "bpython",
    "cabal",
    "python",
    "atuin",
    "treesitter",
    "dunst",
    "scripts",
    "eww",
    "tealdeer",
    "ulauncher",
    "beets",
]
