packages = [
    "emperor",
    "redshift",
    "picom",
    "tmux",
    "neovim",
    "zsh",
    "lisp",
    "bspwm",
    "sway",
    "sxhkd",
    "zathura",
    "mirage",
    "lightdm",
    "taskwarrior",
    "ssh",
    "scripts",
    "emacs",
    "eww",
    "rofi",
    "wofi",
    "tofi",
    "ncmcpp",
    "neomutt",
    "bash",
    "fish",
    "ranger",
    "system",
    "gtk",
    "fonts",
    "shrc",
    "catppuccin",
    "fantasque",
    "alacritty",
    "wezterm",
    "starship",
    "dunst",
    "anki",
    "cli-visualizer",
    "npm",
    "bpython",
    "cabal",
    "python",
    "atuin",
    "treesitter",
    "tealdeer",
    "ulauncher",
]

[files]
# "files/firefox/user.js" = "~/.mozilla/firefox/ogee8zmb.default-release/user.js"
# "files/firefox/userChrome.css" = "~/.mozilla/firefox/ogee8zmb.default-release/chrome/userChrome.css"
# "files/firefox/userContent.css" = "~/.mozilla/firefox/ogee8zmb.default-release/chrome/userContent.css"
