##### Variables #####

# ----- Shell -----
[zsh.variables.shell]
path_to_shell = "/usr/bin/zsh"

# ----- Window Manager -----
[bspwm.variables]
user-session = "bspwm"

# ----- Font -----
[firamono.variables.font]
font = "FiraCode Nerd Font Mono"
font_bold = "FiraCode Nerd Font Mono"
font_italic = "UbuntuMono Nerd Font Mono"
font_bold_italic = "UbuntuMono Nerd Font Mono"
font_size = "11"
font_size_float = "11.0"
[ubuntumono.variables.font]
font = "UbuntuMono Nerd Font Mono"
font_bold = "UbuntuMono Nerd Font Mono"
font_italic = "UbuntuMono Nerd Font Mono"
font_bold_italic = "UbuntuMono Nerd Font Mono"
font_size = "12"
font_size_float = "12.0"
[fantasque.variables.font]
font = "FantasqueSansMono Nerd Font"
font_bold = "FantasqueSansMono Nerd Font"
font_italic = "FantasqueSansMono Nerd Font"
font_bold_italic = "FantasqueSansMono Nerd Font"
font_size = "13"
font_size_float = "13.0"

# ----- Dingspad -----
[dingspad.variables]
disable_touchpad = true
touchpad_xid = 12
display_battery = true
display_wlan = true
multi_monitor = false
ssh_key_name = "id_ed25519"
init_files = "/usr/lib/libfido2.so.1"
init_modules = ""
init_hooks = "base systemd sd-plymouth udev autodetect keyboard keymap sd-vconsole modconf block sd-encrypt lvm2 filesystems fsck"
kernel_parameters_default = "quiet splash loglevel=0 rd.udev.log_priority=0 vt.global_cursor_default=0"
kernel_parameters = "rd.luks.name=267e9431-67d9-4d91-a21b-682396d407ee:parts root=/dev/v/root"
grub_theme = "/boot/themes/monterey-grub-theme/theme.txt"
grub_res = "auto"
# ----- Laptop -----
[laptop.variables]
display_battery = true
display_wlan = true
multi_monitor = false
ssh_key_name = "id_rsa"
init_modules = "i915"
init_hooks = "base udev resume plymouth autodetect modconf block filesystems keyboard fsck"
kernel_parameters = "quiet splash i915.modeset=1 vga=current loglevel=0 rd.udev.log_priority=0 vt.global_cursor_default=0"
grub_theme = "/usr/share/grub/themes/monterey-grub-theme/theme.txt"
grub_res = "auto"
# ----- Desktop -----
[desktop.variables]
display_battery = false
display_wlan = false
multi_monitor = false
second_monitor = "DP-2"
ssh_key_name = "id_rsa"
init_modules = "nvidia nvidia_modeset nvidia_uvm nvidia_drm"
init_hooks = "base udev resume plymouth autodetect modconf block lvm2 filesystems resume keyboard keymap fsck"
kernel_parameters = "quiet loglevel=0 nvidia-drm.modeset=1 splash rd.udev.log_priority=0 vt.global_cursor_default=0 resume=/dev/sdb1 resume_offset=11730944"
grub_theme = "/usr/share/grub/themes/monterey-grub-theme/theme.txt"
grub_res = "1920x1080"
# ----- Server -----
[server.variables]
force_terminfo = true


# ----- Colors -----
[dracula.files]
"files/alacritty/colorschemes/dynamic.yml" = { target = "~/.config/alacritty/colorscheme.yml", type = "template", owner = "b3nj4m1n" }
[dracula.variables.colors]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
# Primary Color
prm = "#bd93f9"
prm_bright = "#D1AEFB"
prm_dim = "#926BD6"
# Secondary Color
scd = "#50fa7b"
scd_bright = "#7BFB8F"
scd_dim = "#3AD771"
# Background Color
bg = "#282a36"
bg_bright = "#6C7086"
bg_dim = "#1D1F2E"
# Foreground Color
fg = "#F8F8F2"
fg_bright = "#FAFAF6"
fg_dim = "#D5D5B0"
# Black
c0 = "#080808" # Normal
c8 = "#050505" # Bright
c16 = "#000000" # Dim
# Red
c1 = "#ff5555" # Normal
c9 = "#FF8A7F" # Bright
c17 = "#DB3E4B" # Dim
# Green
c2 = "#50fa7b" # Normal
c10 = "#7BFB8F" # Bright
c18 = "#3AD771" # Dim
# Yellow
c3 = "#f1fa8c" # Normal
c11 = "#F5FBA8" # Bright
c19 = "#CCD766" # Dim
# Blue
c4 = "#207fdf" # Normal
c12 = "#007fff" # Bright
c20 = "#2873bd" # Dim
# Purple
c5 = "#bd93f9" # Normal
c13 = "#D1AEFB" # Bright
c21 = "#926BD6" # Dim
# Cyan
c6 = "#8be9fd" # Normal
c14 = "#A8F5FD" # Bright
c22 = "#8be9fd" # Dim
# White
c7 = "#ebebeb" # Normal
c15 = "#f5f5f5" # Bright
c23 = "#e8e8e8" # Dim

[catppuccin.files]
"files/alacritty/colorschemes/catppuccin-macchiato.yml" = { target = "~/.config/alacritty/colorscheme.yml", type = "template", owner = "b3nj4m1n" }
[catppuccin.variables.colors]
background = "#24273a"
current_line = "#363a4f"
foreground = "#fcfcfe"
comment = "#6e738d"
cyan = "#8bd5ca"
green = "#a6da95"
orange = "#f5a97f"
pink = "#c6a0f6"
purple = "#b7bdf8"
red = "#ed8796"
yellow = "#eed49f"
# Primary Color
prm = "#8bd5ca"
prm_bright = "#91d7e3"
prm_dim = "#7dc4e4"
# Secondary Color
scd = "#ee99a0"
scd_bright = "#f0c6c6"
scd_dim = "#ed8796"
# Background Color
bg = "#24273a"
bg_bright = "#1e2030"
bg_dim = "#181926"
# Foreground Color
fg = "#fcfcfe"
fg_bright = "#b8c0e0"
fg_dim = "#a5adcb"
# Black
c0 = "#494D64" # Normal
c8 = "#1e2030" # Bright
c16 = "#181926" # Dim
# Red
c1 = "#ee99a0" # Normal
c9 = "#f0c6c6" # Bright
c17 = "#ed8796" # Dim
# Green
c2 = "#A6DA95" # Normal
c10 = "#A6DA95" # Bright
c18 = "#A6DA95" # Dim
# Yellow
c3 = "#EED49F" # Normal
c11 = "#EED49F" # Bright
c19 = "#EED49F" # Dim
# Blue
c4 = "#8AADF4" # Normal
c12 = "#8AADF4" # Bright
c20 = "#8AADF4" # Dim
# Purple
c5 = "#F5BDE6" # Normal
c13 = "#F5BDE6" # Bright
c21 = "#F5BDE6" # Dim
# Cyan
c6 = "#8BD5CA" # Normal
c14 = "#8BD5CA" # Bright
c22 = "#8BD5CA" # Dim
# White
c7 = "#B8C0E0" # Normal
c15 = "#A5ADCB" # Bright
c23 = "#B8C0E0" # Dim



##### Desktop #####

[redshift.files]
"files/redshift/redshift.conf" = "~/.config/redshift.conf"
[lightdm.files]
"files/lightdm/Xsession" = { target = "/etc/lightdm/Xsession", type = "template", owner = "root" }
"files/lightdm/lightdm-gtk-greeter.conf" = { target = "/etc/lightdm/lightdm-gtk-greeter.conf", type = "template", owner = "root" }
"files/lightdm/lightdm-webkit2-greeter.conf" = { target = "/etc/lightdm/lightdm-webkit2-greeter.conf", type = "template", owner = "root" }
"files/lightdm/lightdm.conf" = { target = "/etc/lightdm/lightdm.conf", type = "template", owner = "root" }
[bspwm.files]
"files/bspwm/bspwmrc" = "~/.config/bspwm/bspwmrc"
"scripts/bspwm-resize.sh" = { target = "/usr/bin/scripts/bspwm-resize.sh", type = "template", owner = "root" }
"scripts/bspwm-scratchpad.sh" = { target = "/usr/bin/scripts/bspwm-scratchpad.sh", type = "template", owner = "root" }
"scripts/bspwm-smart-move.sh" = { target = "/usr/bin/scripts/bspwm-smart-move.sh", type = "template", owner = "root" }
"scripts/bspwm-smart-presel.sh" = { target = "/usr/bin/scripts/bspwm-smart-move-presel.sh", type = "template", owner = "root" }
"scripts/bspwm-swap-or-move-in.sh" = { target = "/usr/bin/scripts/bspwm-swap-or-move-in.sh", type = "template", owner = "root" }
[sxhkd.files]
"files/sxhkd/sxhkdrc" = "~/.config/sxhkd/sxhkdrc"
"files/sxhkd/sxhkdrc_bspc" = "~/.config/sxhkd/sxhkdrc_bspc"
[rofi.files]
"files/rofi/config.rasi" = "~/.config/rofi/config.rasi"
"files/rofi/map.csv" = "~/.config/rofi/map.csv"
[fonts.files]
"files/fontconfig/fonts.conf" = "~/.config/fontconfig/fonts.conf"
[polybar.files]
"files/polybar/config" = "~/.config/polybar/config"
"files/polybar/polybar.sh" = "~/.config/polybar/polybar.sh"
"scripts/polybar/powermenu.sh" = { target = "/usr/bin/polyscripts/powermenu.sh", type = "template", owner = "root" }
"scripts/polybar/uptime.sh" = { target = "/usr/bin/polyscripts/uptime.sh", type = "template", owner = "root" }
[gtk.files]
"files/gtk/gtkrc-2.0" = "~/.config/gtk-2.0/gtkrc-2.0"
"files/gtk/settings.ini" = "~/.config/gtk-3.0/settings.ini"
[picom.files]
"files/picom/picom.conf" = "~/.config/picom.conf"
[dunst.files]
"files/dunst/dunstrc" = "~/.config/dunst/dunstrc"
[betterlockscreen.files]
"files/betterlockscreen/betterlockscreenrc" = "~/.config/betterlockscreenrc"


##### GUI Programs #####

[anki.files]
"files/anki/deckbrowser.css" = { target = "/usr/share/aqt_data/web/deckbrowser.css", type = "template", owner = "root" }
"files/anki/editor.css" = { target = "/usr/share/aqt_data/web/editor.css", type = "template", owner = "root" }
"files/anki/overview.css" = { target = "/usr/share/aqt_data/web/overview.css", type = "template", owner = "root" }
"files/anki/reviewer-bottom.css" = { target = "/usr/share/aqt_data/web/reviewer-bottom.css", type = "template", owner = "root" }
"files/anki/reviewer.css" = { target = "/usr/share/aqt_data/web/reviewer.css", type = "template", owner = "root" }
"files/anki/toolbar-bottom.css" = { target = "/usr/share/aqt_data/web/toolbar-bottom.css", type = "template", owner = "root" }
"files/anki/toolbar.css" = { target = "/usr/share/aqt_data/web/toolbar.css", type = "template", owner = "root" }
"files/anki/webview.css" = { target = "/usr/share/aqt_data/web/webview.css", type = "template", owner = "root" }
"files/anki-addons/877182321/meta.json" = "~/.local/share/Anki2/addons21/877182321/meta.json"
[zathura.files]
"files/zathura/zathurarc" = "~/.config/zathura/zathurarc"
[mirage.files]
"files/mirage/settings.json" = "~/.config/mirage/settings.json"
[assets.files]
"scripts/assets/*" = { target = "/usr/bin/scripts/assets/", type = "template", owner = "root" }


##### Shell #####

[starship.files]
"files/starship/starship.toml" = "~/.config/starship.toml"
[shrc.files]
"files/shrc/shrc.sh" = "~/.config/shrc"
[zsh.files]
"files/zsh/zshrc" = "~/.config/zsh/.zshrc"
"files/zsh/zshenv" = { target = "/etc/zshenv", type = "symbolic", owner = "root" }
"files/zsh/zshenv" = { target = "/etc/zsh/zshenv", type = "symbolic", owner = "root" }
[fish.files]
"files/fish/config.fish" = "~/.config/fish/config.fish"
[bash.files]
"files/bash/.bashrc" = "~/.bashrc"
[ssh.files]
"files/ssh/config" = "~/.ssh/config"
[lisp.files]
"files/lisp/init.lisp" = "~/.local/share/roswell/init.lisp"


##### Editors #####

[neovim.files]
"files/nvim/init.lua" = "~/.config/nvim/init.lua"
"files/nvim/ftplugin/c.lua" = "~/.config/nvim/ftplugin/c.lua"
"files/nvim/ftplugin/cpp.lua" = "~/.config/nvim/ftplugin/cpp.lua"
"files/nvim/ftplugin/java.lua" = "~/.config/nvim/ftplugin/java.lua"
"files/nvim/ftplugin/lisp.vim" = "~/.config/nvim/ftplugin/lisp.vim"
"files/nvim/ftplugin/make.lua" = "~/.config/nvim/ftplugin/make.lua"
"files/nvim/ftplugin/markdown.vim" = "~/.config/nvim/ftplugin/markdown.vim"
"files/nvim/ftplugin/norg.vim" = "~/.config/nvim/ftplugin/norg.vim"
"files/nvim/ftplugin/tex.vim" = "~/.config/nvim/ftplugin/tex.vim"
"files/nvim/after/syntax/markdown.vim" = "~/.config/nvim/after/syntax/markdown.vim"
"files/nvim/after/queries/markdown/highlights.scm" = "~/.config/nvim/after/queries/markdown/highlights.scm"
"files/nvim/after/queries/lua/textobjects.scm" = "~/.config/nvim/after/queries/lua/textobjects.scm"
[emacs.files]
"files/doom/config.org" = "~/.config/doom/config.org"
"files/doom/init.el" = "~/.config/doom/init.el"
"files/doom/packages.el" = "~/.config/doom/packages.el"


##### Terminal #####

[alacritty.files]
"files/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"
[wezterm.files]
"files/wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"
[tmux.files]
"files/tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
# "files/tmux/tmux.conf.home" = "~/.tmux.conf"
"scripts/tmuxleft.sh" = { target = "/usr/bin/scripts/tmuxleft.sh", type = "template", owner = "root" }
"scripts/tmuxright.sh" = { target = "/usr/bin/scripts/tmuxright.sh", type = "template", owner = "root" }
"scripts/tmuxstssrc.sh" = { target = "/usr/bin/scripts/tmuxstssrc.sh", type = "template", owner = "root" }
[taskwarrior.files]
"files/taskwarrior/taskrc" = "~/.config/task/taskrc"
"files/taskwarrior/hooks/on-modify.timewarrior" = "~/.config/task/hooks/on-modify.timewarrior"
"files/timewarrior/timewarrior.cfg" = "~/.local/share/timew/timewarrior.cfg"
[ncmcpp.files]
"files/ncmpcpp/config" = "~/.config/ncmpcpp/config"
"files/ncmpcpp/bindings" = "~/.config/ncmpcpp/bindings"
[neomutt.files]
"files/mutt/settings.muttrc" = "~/.config/mutt/settings.muttrc"
[ranger.files]
"files/ranger/rc.conf" = "~/.config/ranger/rc.conf"
"files/ranger/scope.sh" = "~/.config/ranger/scope.sh"
[cli-visualizer.files]
"files/cli-visualizer/config" = "~/.config/vis/config"
"files/cli-visualizer/colors/dracula" = "~/.config/vis/colors/dracula"
[scripts.files]
"scripts/compile.sh" = { target = "/usr/bin/compile", type = "template", owner = "root" }
"scripts/run.sh" = { target = "/usr/bin/run", type = "template", owner = "root" }
"scripts/backup_sh_history.sh" = { target = "/usr/bin/scripts/backup_sh_history.sh", type = "template", owner = "root" }
"scripts/colors.sh" = { target = "/usr/bin/scripts/colors.sh", type = "template", owner = "root" }
"scripts/bw-wrapper.sh" = { target = "/usr/bin/scripts/bw-wrapper.sh", type = "template", owner = "root" }
"scripts/emoji-picker.sh" = { target = "/usr/bin/scripts/emoji-picker.sh", type = "template", owner = "root" }
"scripts/fav-song.sh" = { target = "/usr/bin/scripts/fav-song.sh", type = "template", owner = "root" }
"scripts/keyboard-layout-switcher.sh" = { target = "/usr/bin/scripts/keyboard-layout-switcher.sh", type = "template", owner = "root" }
"scripts/mpd-status.sh" = { target = "/usr/bin/scripts/mpd-status.sh", type = "template", owner = "root" }
"scripts/mpd-open-playlist.sh" = { target = "/usr/bin/scripts/mpd-open-playlist.sh", type = "template", owner = "root" }
"scripts/open-move.sh" = { target = "/usr/bin/scripts/open-move.sh", type = "template", owner = "root" }
"scripts/play-song.sh" = { target = "/usr/bin/scripts/play-song.sh", type = "template", owner = "root" }
"scripts/program-launcher.sh" = { target = "/usr/bin/scripts/program-launcher.sh", type = "template", owner = "root" }
"scripts/sxhkd-help-page.sh" = { target = "/usr/bin/scripts/sxhkd-help-page.sh", type = "template", owner = "root" }
"scripts/take-screenshot.sh" = { target = "/usr/bin/scripts/take-screenshot.sh", type = "template", owner = "root" }
"scripts/wally.sh" = { target = "/usr/bin/scripts/wally.sh", type = "template", owner = "root" }
"scripts/auto_commit.sh" = { target = "/usr/bin/scripts/auto_commit.sh", type = "template", owner = "root" }
"scripts/extract_norg.sh" = { target = "/usr/bin/scripts/extract_norg.sh", type = "template", owner = "root" }
"scripts/filestat.sh" = { target = "/usr/bin/scripts/filestat.sh", type = "template", owner = "root" }
[npm.files]
"files/npm/npmrc" = "~/.config/npm/npmrc"
[bpython.files]
"files/bpython/config" = "~/.config/bpython/config"
[cabal.files]
"files/cabal/config" = "~/.config/cabal/config"
[python.files]
"files/python/pythonrc" = "~/.config/python/pythonrc"
[atuin.files]
"files/atuin/config.toml" = "~/.config/atuin/config.toml"
[treesitter.files]
"files/tree-sitter/config.json" = "~/.config/tree-sitter/config.json"


##### System #####

[system.files]
"files/etc/profile" = { target = "/etc/profile", type = "template", owner = "root" }
"files/etc/pacman.conf" = { target = "/etc/pacman.conf", type = "template", owner = "root" }
"files/etc/mkinitcpio.conf" = { target = "/etc/mkinitcpio.conf", type = "template", owner = "root" }
"files/etc/grub" = { target = "/etc/default/grub", type = "template", owner = "root" }
"files/etc/plymouth.conf" = { target = "/etc/plymouth/plymouthd.conf", type = "template", owner = "root" }
"files/etc/sudoers.d/suspend" = { target = "/etc/sudoers.d/suspend", type = "symbolic", owner = "root" }
"files/etc/bluetooth/main.conf" = { target = "/etc/bluetooth/main.conf", type = "template", owner = "root" }
