##### Variables #####

# ----- Shell -----
[zsh.variables.shell]
path_to_shell = "/usr/bin/zsh"

# ----- Window Manager -----
[bspwm.variables]
user-session = "bspwm"

# ----- Font -----
[firamono.variables.font]
font = "FiraMono Nerd Font Mono"
font_bold = "FiraMono Nerd Font Mono"
font_italic = "UbuntuMono Nerd Font Mono"
font_bold_italic = "UbuntuMono Nerd Font Mono"
font_size = "11"
font_size_float = "11.0"
[ubuntumono.variables.font]
font = "UbuntuMono Nerd Font Mono"
font_bold = "UbuntuMono Nerd Font Mono"
font_italic = "UbuntuMono Nerd Font Mono"
font_bold_italic = "UbuntuMono Nerd Font Mono"
font_size = "12"
font_size_float = "12.0"

# ----- Laptop -----
[laptop.variables]
display_battery = true
display_wlan = true
# ----- Desktop -----
[desktop.variables]
display_battery = false
display_wlan = false
# ----- Server -----
[server.variables]
force_terminfo = true


# ----- Colors -----
[dracula.variables.colors]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
# Primary Color
prm = "#bd93f9"
prm_bright = "#D1AEFB"
prm_dim = "#926BD6"
# Secondary Color
scd = "#50fa7b"
scd_bright = "#7BFB8F"
scd_dim = "#3AD771"
# Background Color
bg = "#282a36"
bg_bright = "#6C7086"
bg_dim = "#1D1F2E"
# Foreground Color
fg = "#F8F8F2"
fg_bright = "#FAFAF6"
fg_dim = "#D5D5B0"
# Black
c0 = "#080808" # Normal
c8 = "#050505" # Bright
c16 = "#000000" # Dim
# Red
c1 = "#ff5555" # Normal
c9 = "#FF8A7F" # Bright
c17 = "#DB3E4B" # Dim
# Green
c2 = "#50fa7b" # Normal
c10 = "#7BFB8F" # Bright
c18 = "#3AD771" # Dim
# Yellow
c3 = "#f1fa8c" # Normal
c11 = "#F5FBA8" # Bright
c19 = "#CCD766" # Dim
# Blue
c4 = "#207fdf" # Normal
c12 = "#007fff" # Bright
c20 = "#2873bd" # Dim
# Purple
c5 = "#bd93f9" # Normal
c13 = "#D1AEFB" # Bright
c21 = "#926BD6" # Dim
# Cyan
c6 = "#8be9fd" # Normal
c14 = "#A8F5FD" # Bright
c22 = "#8be9fd" # Dim
# White
c7 = "#ebebeb" # Normal
c15 = "#f5f5f5" # Bright
c23 = "#e8e8e8" # Dim



##### Desktop #####

[lightdm.files]
"files/lightdm/Xsession" = "/etc/lightdm/Xsession"
"files/lightdm/lightdm-gtk-greeter.conf" = "/etc/lightdm/lightdm-gtk-greeter.conf"
"files/lightdm/lightdm-webkit2-greeter.conf" = "/etc/lightdm/lightdm-webkit2-greeter.conf"
"files/lightdm/lightdm.conf" = "/etc/lightdm/lightdm.conf"
[bspwm.files]
"files/bspwm/bspwmrc" = "~/.config/bspwm/bspwmrc"
"scripts/bspwm-focus.sh" = "/usr/bin/scripts/bspwm-focus.sh"
"scripts/bspwm-resize-old.sh" = "/usr/bin/scripts/bspwm-resize-old.sh"
"scripts/bspwm-resize.sh" = "/usr/bin/scripts/bspwm-resize.sh"
"scripts/bspwm-scratchpad.sh" = "/usr/bin/scripts/bspwm-scratchpad.sh"
"scripts/bspwm-smart-move.sh" = "/usr/bin/scripts/bspwm-smart-move.sh"
"scripts/bspwm-smart-presel.sh" = "/usr/bin/scripts/bspwm-smart-move-presel.sh"
"scripts/bspwm-swap-or-move-in.sh" = "/usr/bin/scripts/bspwm-swap-or-move-in.sh"
[sxhkd.files]
"files/sxhkd/sxhkdrc" = "~/.config/sxhkd/sxhkdrc"
"files/sxhkd/sxhkdrc_bspc" = "~/.config/sxhkd/sxhkdrc_bspc"
[rofi.files]
"files/rofi/config.rasi" = "~/.config/rofi/config.rasi"
"files/rofi/map.csv" = "~/.config/rofi/map.csv"
[fonts.files]
"files/fontconfig/fonts.conf" = "~/.config/fontconfig/fonts.conf"
[polybar.files]
"files/polybar/config" = "~/.config/polybar/config"
"files/polybar/polybar.sh" = "~/.config/polybar/polybar.sh"
"scripts/polybar/powermenu.sh" = "/usr/bin/polyscripts/powermenu.sh"
"scripts/polybar/uptime.sh" = "/usr/bin/polyscripts/uptime.sh"
[gtk.files]
"files/gtk/gtkrc-2.0" = "~/.config/gtk-2.0/.gtkrc-2.0"
"files/gtk/settings.ini" = "~/.config/gtk-3.0/settings.ini"
[picom.files]
"files/picom/picom.conf" = "~/.config/picom.conf"
[dunst.files]
"files/dunst/dunstrc" = "~/.config/dunst/dunstrc"
[betterlockscreen.files]
"files/betterlockscreen/betterlockscreenrc" = "~/.config/betterlockscreenrc"


##### GUI Programs #####

[anki.files]
"files/anki/deckbrowser.css" = "/usr/share/aqt_data/web/deckbrowser.css"
"files/anki/editor.css" = "/usr/share/aqt_data/web/editor.css"
"files/anki/overview.css" = "/usr/share/aqt_data/web/overview.css"
"files/anki/reviewer-bottom.css" = "/usr/share/aqt_data/web/reviewer-bottom.css"
"files/anki/reviewer.css" = "/usr/share/aqt_data/web/reviewer.css"
"files/anki/toolbar-bottom.css" = "/usr/share/aqt_data/web/toolbar-bottom.css"
"files/anki/toolbar.css" = "/usr/share/aqt_data/web/toolbar.css"
"files/anki/webview.css" = "/usr/share/aqt_data/web/webview.css"
"files/anki-addons/877182321/meta.json" = "~/.local/share/Anki2/addons21/877182321/meta.json"
[zathura.files]
"files/zathura/zathurarc" = "~/.config/zathura/zathurarc"
[mirage.files]
"files/mirage/settings.json" = "~/.config/mirage/settings.json"
[assets.files]
"scripts/assets/*" = "/usr/bin/scripts/assets/"


##### Shell #####

[starship.files]
"files/starship/starship.toml" = "~/.config/starship.toml"
[shrc.files]
"files/shrc/shrc.sh" = "~/.config/shrc"
[zsh.files]
"files/zsh/zshrc" = "~/.config/zsh/.zshrc"
"files/zsh/zshrc.home" = "~/.zshrc"
[fish.files]
"files/fish/config.fish" = "~/.config/fish/config.fish"
[bash.files]
"files/bash/.bashrc" = "~/.bashrc"
[ssh.files]
"files/ssh/config" = "~/.ssh/config"


##### Editors #####

[neovim.files]
"files/nvim/init.lua" = "~/.config/nvim/init.lua"
"files/nvim/lua/plugins.lua" = "~/.config/nvim/lua/plugins.lua"
"files/nvim/lua/plugin-config.lua" = "~/.config/nvim/lua/plugin-config.lua"
"files/nvim/lua/functions.lua" = "~/.config/nvim/lua/functions.lua"
"files/nvim/lua/binds.lua" = "~/.config/nvim/lua/binds.lua"
"files/nvim/lua/opts.lua" = "~/.config/nvim/lua/opts.lua"
"files/nvim/lua/compile.lua" = "~/.config/nvim/lua/compile.lua"
"files/nvim/ftplugin/tex.vim" = "~/.config/nvim/ftplugin/tex.vim"
"files/nvim/ftplugin/markdown.vim" = "~/.config/nvim/ftplugin/markdown.vim"
"files/nvim/after/syntax/markdown.vim" = "~/.config/nvim/after/syntax/markdown.vim"
"files/nvim/after/queries/markdown/highlights.scm" = "~/.config/nvim/after/queries/markdown/highlights.scm"
[emacs.files]
"files/doom/config.org" = "~/.config/doom/config.org"
"files/doom/init.el" = "~/.config/doom/init.el"
"files/doom/packages.el" = "~/.config/doom/packages.el"


##### Terminal #####

[alacritty.files]
"files/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"
[tmux.files]
"files/tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
"files/tmux/tmux.conf.home" = "~/.tmux.conf"
"scripts/tmuxleft.sh" = "/usr/bin/scripts/tmuxleft.sh"
"scripts/tmuxright.sh" = "/usr/bin/scripts/tmuxright.sh"
"scripts/tmuxstssrc.sh" = "/usr/bin/scripts/tmuxstssrc.sh"
[ncmcpp.files]
"files/ncmpcpp/config" = "~/.config/ncmpcpp/config"
"files/ncmpcpp/bindings" = "~/.config/ncmpcpp/bindings"
[neomutt.files]
"files/mutt/settings.muttrc" = "~/.config/mutt/settings.muttrc"
[ranger.files]
"files/ranger/rc.conf" = "~/.config/ranger/rc.conf"
"files/ranger/scope.sh" = "~/.config/ranger/scope.sh"
[cli-visualizer.files]
"files/cli-visualizer/config" = "~/.config/vis/config"
"files/cli-visualizer/colors/dracula" = "~/.config/vis/colors/dracula"
[scripts.files]
"scripts/compile.sh" = "/usr/bin/compile"
"scripts/run.sh" = "/usr/bin/run"
"scripts/compile_run.sh" = "/usr/bin/compile_run"
"scripts/bw-wrapper.sh" = "/usr/bin/scripts/bw-wrapper.sh"
"scripts/compile-latex.sh" = "/usr/bin/scripts/compile-latex.sh"
"scripts/dmenu-mount.sh" = "/usr/bin/scripts/dmenu-mount.sh"
"scripts/dmenu-umount.sh" = "/usr/bin/scripts/dmenu-umount.sh"
"scripts/draw-terminal.sh" = "/usr/bin/scripts/draw-terminal.sh"
"scripts/emoji-picker.sh" = "/usr/bin/scripts/emoji-picker.sh"
"scripts/fav-song.sh" = "/usr/bin/scripts/fav-song.sh"
"scripts/keyboard-layout-switcher.sh" = "/usr/bin/scripts/keyboard-layout-switcher.sh"
"scripts/mpd-status.sh" = "/usr/bin/scripts/mpd-status.sh"
"scripts/mpd-open-playlist.sh" = "/usr/bin/scripts/mpd-open-playlist.sh"
"scripts/open-move.sh" = "/usr/bin/scripts/open-move.sh"
"scripts/play-song.sh" = "/usr/bin/scripts/play-song.sh"
"scripts/process-bay.sh" = "/usr/bin/scripts/process-bay.sh"
"scripts/program-launcher.sh" = "/usr/bin/scripts/program-launcher.sh"
"scripts/start-lemonbar.sh" = "/usr/bin/scripts/start-lemonbar.sh"
"scripts/sxhkd-help-page.sh" = "/usr/bin/scripts/sxhkd-help-page.sh"
"scripts/take-screenshot.sh" = "/usr/bin/scripts/take-screenshot.sh"
[profile.files]
"files/etc/profile" = "/etc/profile"
"files/etc/pacman.conf" = "/etc/pacman.conf"
