packages = [
    "server",
    "ssh",
    "tmux",
    "neovim",
    "zsh",
    "bash",
    "scripts",
    "profile",
    "system",
    "fonts",
    "shrc",
    "dracula",
    "firamono",
    "starship",
    "npm",
    "bpython",
]
