#!/usr/bin/env sh

# https://unix.stackexchange.com/a/230533
print_volume() {
    pactl list sinks | grep '^[[:space:]]Volume:' | \
        head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
}

volume=$(print_volume)
printf "\n%s\n" "$volume"
pactl subscribe | while read -r _ ; do
    new_volume=$(print_volume)
    if [ "$volume" != "$new_volume" ]; then
        volume="$new_volume"
        printf "\n%s\n" "$volume"
    fi
done
